package com.ipdive.springboottemplate.logic;

public enum EmailBodyTemplates {
    PASSWORD_RESET_EMAIL("<html><p>This email was autogenerated because you requested a password reset " +
            "for your account on the website " + Constants.WEBSITE_NAME + "<br><br>" +
            "Please click the button below and follow the instructions.<br><br>" +
            "<a href=\"" + Constants.RESET_PASSWORD_URL + "?token=%s\"><button type=\"button\">Reset your password</button></a><br><br>" +
            "If the button isn't working, paste the following URL into your browser:<br>" +
            Constants.RESET_PASSWORD_URL + "?token=%s</p></html>",
            "Password reset requested"),

    CONTACT_FORM_EMAIL("<html><p>This is a message from contact form.<br><br>" +
            "First name: %s <br>" +
            "Last name: %s <br>" +
            "Email: %s <br>" +
            "Phone number: %s <br>" +
            "Message: %s <br>",
            "Contact form from numberoneshares.com"),

    ACCOUNT_VALIDATION_EMAIL("<html><p>This is autogenerated email from the numberoneshares.com website.<br><br>" +
            "If you didn't create a new account on numberoneshares.com, you can ignore this email.<br><br>" +
            "Please validate your account by clicking on the button below.<br><br>" +
            "<a href=\"" + Constants.ACCOUNT_VALIDATION_URL + "?username=%s\"><button type=\"button\">Validate your account</button></a><br><br>" +
            "If the button isn't working, paste the following URL into your browser:<br>" +
            Constants.ACCOUNT_VALIDATION_URL + "?username=%s</p></html>" +
            "The activation link is available only for the next 24 hours. Afterwards you account will be deleted.",
            "Validate your email at numberoneshares.com");

    private final String emailBody;
    private final String emailSubject;

    EmailBodyTemplates(String emailBody, String emailSubject) {
        this.emailBody = emailBody;
        this.emailSubject = emailSubject;
    }

    public String getEmailBody() {
        return emailBody;
    }

    public String getEmailSubject() {
        return emailSubject;
    }

    public static class Constants {
        private static final String WEBSITE_NAME = "numberoneshares.com";
        private static final String RESET_PASSWORD_PAGE = "resetPassword";
        private static final String RESET_PASSWORD_URL = WEBSITE_NAME + "/" + RESET_PASSWORD_PAGE;
        private static final String ACCOUNT_VALIDATION_PAGE = "validateAccount";
        private static final String ACCOUNT_VALIDATION_URL = WEBSITE_NAME + "/" + ACCOUNT_VALIDATION_PAGE;
    }
}
